### ISSUE TITLE
Bulk tip creation feedback 

### ISSUE THREAD

**Issue by juangb87** [lightsats/lightsats#113]
@rolznz this is something we can put more thought, when creating Bulk Tips if they don't get funded maybe we have a way to just delete the group.

Also if you fund 10 and only use a few maybe have a way of reclaiming all at once instead of individually.

-------------
From Steffen:

I have created a batch of 10 claims, and that worked great as before...

But now I found out, I don't need them after all, and only 1 got used - so I wanted to defund/cancel the remainders... But now I think I have to go through them one by one and cancel them... 

A "Delete all unclaimed tips in this batch" function would be a nice little improvement on the Batch tipping feature... If that makes sense :)
-------------

**Comment by rolznz** [comment]
I think the bulk tips and tips can only be deleted if the bulk tip hasn't been funded yet.

If the bulk tip has been funded, we should have a "Reclaim unwithdrawn tips" button which will reclaim them all in one go

**Comment by rolznz** [comment]
This has been implemented!
