### ISSUE TITLE
Proposal for bulk tips:

### ISSUE THREAD

**Issue by SteffenWOTSdk** [lightsats/lightsats#124]
Proposal for bulk tips:

- An option to bulk change the "Anon" label for give-aways to something else
- Clickable "copy link" button next to the links in "View bulk links" function
- an "already copied" ticker next to that 

Reason for proposals: 
1. I would like the Anon label changed in bulk to for instance be "commenter" or "participant"
2. sometimes I can't tell where I've gotten to in the queue, when manually copying and pasting links to receipients one by one

![image](https://user-images.githubusercontent.com/122060005/210892361-bbed750c-b3ca-4af2-b838-3f65697e6404.png)

![image](https://user-images.githubusercontent.com/122060005/210892251-c6f7bd44-cd26-4248-96bf-fcf8fe40efdd.png)

_Originally posted by @SteffenWOTSdk in https://github.com/lightsats/lightsats/issues/34#issuecomment-1372875029_

**Comment by rolznz** [comment]
@SteffenWOTSdk thanks for the feedback. 

1. I also think entering recipient names right now is not good. Maybe we could toggle between two input types (one per line OR a generic name that can be templated, e.g. commenter #{{number}} (would translate to commenter #1, commenter #2, ...)

2. Should we show the tip status there too (seen/unseen?) or would it be better to add a copy button on the individual tips (if you scroll further down)?

We also think this method of manually copying and pasting is painful. Would it help to have a SINGLE link which will redirect randomly to one of the unclaimed tips if there is one? (Note: we have to be careful here to stop one person from claiming all the tips themselves)

**Comment by SteffenWOTSdk** [comment]
1. I like the toggle solution, that would give me the ease of use I want when gifting to someone with "generic" nicks vs. individual usernames, that sound like a winning feature to me.
OR maybe just present the option to change the Anon nick, before creating the batch in the form of an optional input field.
If I don't write in a custom nick to use for the entire list, it just defaults to Anon.
But if I do input something, they all change and get presented in the same way as now. and then I can also individually alter the name in the same way as currently, allowing me to use a batch tip for both targeted and untargeted gifting.

2. This one is definitely the harder of the two.
Maybe - and I don't know if this is even possible - but maybe, the links could be listed as clickable in some markdown format, that results in: When I click the individual link on the list, it copies the link to my clipboard, and changes the link font colour.
That way I know if the link has been used, and it solves the copy/paste in-elegance. 

Would this be a possible solution?

I think the single link solution is too open to gamifying as you mentioned, so I don't think that would be a good option, it will just incetivize bad acting, and possibly devalue the great work already put into this app.

**Comment by rolznz** [comment]
@SteffenWOTSdk for now it might just be easier to have a "copy all" button and individual copy buttons for each link rather than having to do some sort of markdown solution


I'll let you know when I have something ready for testing/feedback.

**Comment by SteffenWOTSdk** [comment]
sounds like a plan

**Comment by rolznz** [comment]
@SteffenWOTSdk just to confirm, for the issue when copying and sending tips is it's just easy to lose your place, would it work for us to add a new property to the tip to show whether or not it's been copied? This way the status would persist if you exit Lightsats and re-open it later.

This only seems necessary for bulk tips that you send links out for. For printed cards we don't need this status because we have a physical card that we know we have handed out.

So that it only appears when you actually want to view this status, we are thinking of adding it to a new dropdown - when you click on this item it could open a new page with a list of the tips, each with a copy button attached to it, either saying "copy or copied (time it was copied here)".
![image](https://user-images.githubusercontent.com/33993199/212059188-9d3489bc-2764-48a0-b8f2-e50a30e7b996.png)

Original idea from @reneaaron

**Comment by SteffenWOTSdk** [comment]
Hi @rolznz 

Yes, exactly - that's the only problem I personally am having. They line up with the order of the editing below, so I have not had any trouble matching up copied links with usernames, even on larger batches, that's simply a matter of counting from bottom or top usually. KISS (Keep it simple & sweet)

So in the same way as a markdown colour-change would be sufficient, showing whether the link has already been copied/used would solve this issue (for me at least).

Definitely sounds like another winner in my book!

**Comment by rolznz** [comment]
@SteffenWOTSdk thanks! the copy tips functionality is up on production - let me know what you think! 
![image](https://user-images.githubusercontent.com/33993199/212304784-556fa108-3984-4d67-a82a-65a368fcfc8c.png)
![image](https://user-images.githubusercontent.com/33993199/212304860-c3261ee8-4140-4399-9b8b-e8a15f390214.png)

**Comment by SteffenWOTSdk** [comment]
![image](https://user-images.githubusercontent.com/122060005/212410459-abddac71-ba92-484d-9a90-85b030d29d08.png)

Very nice @rolznz  - took a second to figure out the "config wheel" was where I needed to go, even though you made it pretty obvs above - nothing major.

It's second nature now, but maybe there is a slightly more intuitive Icon you could use for the dropdown? - not sure what it would be though...

Overall it's a really nice solution, and not having to copy/paste text lines is a major improvement for sure.

**Comment by rolznz** [comment]
@SteffenWOTSdk thanks!

@reneaaron any thoughts on this? Maybe we could have some text next to the icon, like "Manage" or something.
Maybe Steffen it's because you have been using this interface a lot already, and just simply missed it since it's quite a small button on the top right.

**Comment by SteffenWOTSdk** [comment]
I had both those thought as well to be fair @rolznz and it's not like I spent hours or even minutes looking around in bewilderment... 

Found the "config wheel" menu rather quickly, since it's really the only place you can go to do anything once the bulk tips are created 🤷‍♂️ 

I do tend to agree with the "Manage" idea you set forth here though - I thought about suggesting "More" as it was the only thing that came to mind, but it didn't really cover or clarify, so I didn't think it was an improvement.

"Manage" or "Manage (bulk) tips" would be totally clear in my mind however - so I suggest that as a possible solution to what may turn out to be a complete non-issue. 😄

**Comment by rolznz** [comment]
@SteffenWOTSdk I've made that change and also improved the recipient name input for bulk. You can use a template like "commenter" or "commenter #{{index}}" if you'd like each recipient name to have a number next to them (commenter #1, commenter #2,...)

Please let me know if this works for you :-)

**Comment by reneaaron** [comment]
@rolznz "Manage" sounds like a good name to me. That should make it more obvious 👍

**Comment by rolznz** [comment]
@SteffenWOTSdk I will close this ticket now as I believe I have addressed the issues. If you have any additional feedback, please create a new issue!
