### ISSUE TITLE
When sending out links, it needs to be clearer that no e-mail or phone number is REQUIRED, but only optional

### ISSUE THREAD

**Issue by SteffenWOTSdk** [lightsats/lightsats#125]
I am getting a lot of responses from people when gifting, who are already on LN, but overlook the "lightning" option, when it defaults to use of phone number for oboarding.

I can't use the "skip onboarding" function on a batch because; when doing a giveaway of say 100 x 100 sats, I have no idea if the person is or isn't onboarded, so that would add a step of me asking if they need the onboarding or not.

The recipient could be a person getting their VERY first sats, or a hardcore stacker, and I won't know, unless I ask, and I can't ask 100 ppl if they are already on LN or not. 

So that "Lightning onboarding/Already on LN" added option would be the solution for me in my case.

I want to be able to ALWAYS just use LightSats in the same way, no matter who I am sending links to, or it will start being too extensive of an experience for me to tip/gift sats vs. onboarding... The beauty of LightSats is that I can send it to whoever, no matter if I am tipping or OP'ing. If that makes sense?

_Originally posted by @SteffenWOTSdk in https://github.com/lightsats/lightsats/issues/34#issuecomment-1373135174_

**Comment by rolznz** [comment]
This is a difficult one because for absolute newbies it's easier for them to authenticate with phone number. However, if you're sending out links (or printed cards) I think using the upcoming "Lightning Onboarding" feature would work because they can always re-open the original link without us worrying they will lose their session. 

If you're tipping in person and asking them to scan, I think letting them sign up with phone number is the easiest option, and they'll also be reminded to withdraw their sats periodically.

I will ask @reneaaron and @juangb87  for their thoughts on this

**Comment by SteffenWOTSdk** [comment]
I will say, this is mostly a problem for people who are already onboarded on LN and get suspicious about having to do "KYC" like actions, So once they get told there IS a lightning option, and see it, they immediately understand. 

The REAL problem is simply, that the Lightning option is not immediately noticeable. I think moving the e-mail and lightning option above the input field, or just making it more visible below, would immediately solve this.

**Comment by rolznz** [comment]
> I will say, this is mostly a problem for people who are already onboarded on LN and get suspicious about having to do "KYC" like actions, So once they get told there IS a lightning option, and see it, they immediately understand.
> 
> The REAL problem is simply, that the Lightning option is not immediately noticeable. I think moving the e-mail and lightning option above the input field, or just making it more visible below, would immediately solve this.

It would solve this particular issue, but it would not be user-friendly for nocoiners, because we don't want to introduce too many options and the easiest way for them to start is by phone number.

**Comment by SteffenWOTSdk** [comment]
Fair point, it's always a question of finding that sweet spot in the middle/golden middle-road

**Comment by reneaaron** [comment]
Thanks for your feedback @SteffenWOTSdk. I did another iteration on the sign in options: 

![image](https://user-images.githubusercontent.com/100827540/211217094-dcbe8450-b88f-4c85-b7d4-3f5f1fda0a64.png)

Do you think that is an improvement?

**Comment by SteffenWOTSdk** [comment]
YES! I think you just hit this out of the park!!!

If people still complain, then it can't be called your fault anymore with this setup IMO! 

This would do exactly what you need IMHO.

**Comment by SteffenWOTSdk** [comment]
Maybe the wording should be "Other ways to Claim" - just to be 100% clear, but otherwise, spot on!

**Comment by reneaaron** [comment]
Thanks for your feedback @SteffenWOTSdk, great to have you here! 👍

**Comment by SteffenWOTSdk** [comment]
Pleasure to be lending a small hand to a great project!!! 

Keep up the good work guys - have had no first-timers come back since we last spoke, and I have also just become better and iterating that the opportunity for skipping right to Lightning option exists, so it's a combo of informing upfront and visibility of the option, I think - let's assume this 'issue' is resolved... 👍
