### ISSUE TITLE
Feature Request: Denominate tip amount in sats

### ISSUE THREAD

**Issue by librethanks** [lightsats/lightsats#135]
On the tip creation page, /tips/new, allow the user to price tips in sats rather than only choosing fiat currency and calculating conversion rate.

For example:

-the user wants to tip exactly 5000 satoshis
-currently has to calculate backwards to get the current exchange rate for fiat to get exactly 5000

**Comment by rolznz** [comment]
Hi @librethanks 

You can click this button to toggle between sats and fiat. 
![image](https://user-images.githubusercontent.com/33993199/213702002-7aed3ff8-5da6-4688-8613-a2271cbc2a27.png)

Let us know if you think there would be a more obvious way to do this!

**Comment by librethanks** [comment]
Thank you, I had no idea.

I think a different icon could work. Maybe have the button to swap outside of the form field and continue to use the currency symbol inside of the field.

Here is what Breez uses:
![Screenshot_20230121-164415_1.png](https://user-images.githubusercontent.com/97930095/213888191-714ee138-5b61-4b53-a59b-2d0c2e425d4e.png)

**Comment by rolznz** [comment]
@librethanks thanks! I like that style of icon, I think it's much more obvious than our current one.

**Comment by lujakob** [comment]
I had the same issue: wanted to switch to Sats but didn't know how. I thought it's not possible. I clicked something and got the impression I can only switch between Fiat currencies.

**Comment by rolznz** [comment]
@lujakob @librethanks this is the new design (not deployed yet). What do you think?
![image](https://user-images.githubusercontent.com/33993199/216874259-372b5c85-682e-4a1e-8a03-4ecd2b9b9a09.png)

**Comment by rolznz** [comment]
This is up in production now! let me know if you have any further thoughts, otherwise I'll close this issue.

**Comment by lujakob** [comment]
To me the intention behind is communicated clearly. I get it.

**Comment by rolznz** [comment]
Thanks! In that case, I'll close the issue. Feel free to open a new one if you have any more feedback 🚀
