### ISSUE TITLE
docker-compose postgres user "user" not working

### ISSUE THREAD

**Issue by lujakob** [lightsats/lightsats#143]
I'm not sure how you created a user with the value "user" in Postgres. I was not able to do this with the shell. I suspect that a "user" of name "user" is not allowed. In the end I needed to try "newuser" which worked.

I tried it with 

```
postgres-> CREATE ROLE user WITH LOGIN PASSWORD 'password';
ERROR:  syntax error at or near "user"
LINE 1: CREATE USER user
```

The issue is, I need to change the docker-compose.yml and it is commited to the repo. Is there a way to create a "user" user or could the docker-compose file be changed to pick up params from the cli?

https://github.com/lightsats/lightsats/blob/main/app/docker-compose.yml#L10

**Comment by rolznz** [comment]
This might be because of a conflict with the local postgres service. I have updated the README regarding this. Please let me know if that fixes the issue!

**Comment by lujakob** [comment]
Yes it works. Thanks.
