### ISSUE TITLE
Bug: trying to link a wallet that is already linked to a different account

### ISSUE THREAD

**Issue by rolznz** [lightsats/lightsats#146]
Currently this will make you log into the other account.

It should fail when you try to link with an error message (this wallet is already in use)

**Comment by lujakob** [comment]
@rolznz I could also look into this. (Unless it makes more sense you fix it yourself.) But I'm not sure how to reproduce it. At what point do I link a wallet? How exactly can I reproduce it?

**Comment by rolznz** [comment]
Sure, thanks!. When you login with lightning you can create an account connected to the wallet you logged in.

Then create a new account but this time sign up with email. Go to your profile => Linked accounts and try to link the lightning wallet you already created an account with above.

**Comment by rolznz** [comment]
Fixed on production - will look like this:

![image](https://user-images.githubusercontent.com/33993199/218245286-4bc1cabd-88c7-4fe2-9f3a-ad8b7558e14c.png)
