### ISSUE TITLE
Bug: standard onboarding is not selected by default in advanced settings (new tips)

### ISSUE THREAD

**Issue by rolznz** [lightsats/lightsats#147]
![image](https://user-images.githubusercontent.com/33993199/217015679-ca9655f9-1d23-463d-8ae1-4cb0c4f8b1aa.png)

**Comment by lujakob** [comment]
@rolznz I found the problem and created a PR for this.

**Comment by lujakob** [comment]
@rolznz this can be closed, right?

**Comment by rolznz** [comment]
@lujakob I haven't deployed the changes yet, I'll close it then. Thanks!
