### ISSUE TITLE
UX: odd wording in popup during tip creation

### ISSUE THREAD

**Issue by niclaz** [lightsats/lightsats#152]
During the creation of a new tip (first time testing this feature) I found the wording of this popup (screenshot) odd:

![popup error lightsats](https://user-images.githubusercontent.com/83479948/218398059-4c87aca4-070e-4475-9494-f27c14fecdc3.png)

This was when I was trying to make a tip 0.00000001 BTC and after trying to create the tip (create tip button) the popup appears saying that my integer was wrong... this makes sense with the other fiat options as all of those do not go below 1 cent (0.01 of base currency) but less so for BTC. 

This is a different error if the tip amount is too small which appears at bottom of the page and has a red colored cross icon within it. 

Furthermore the closest real integer might be zero/0 as the popup suggests but that is not what you want to user to select as it will later give them an error that the amount is too small

**Issue**: Wording of the popup was strange and affects user experience

**Suggestion**: replace this popup with the same as the 'amount is too small' popup that appears at the bottom of the page, and create specific integer range for BTC which does not follow the fiat currency logic of 0.01 being the lowest possible amount.

Nice work overall everyone, I like what you have built here.

OS: Linux
Browser: Firefox 109.0.1 (64-bit)

**Comment by rolznz** [comment]
@niclaz thanks!

What if when you select BTC in the dropdown you are only able to enter the value in sats? I think it's a better UX than entering 0.0001 or whatever value you want to choose which is less than 0.01?

![image](https://user-images.githubusercontent.com/33993199/218437655-1cc975f9-db52-4a7d-8b50-a4f0f6eca8d1.png)

**Comment by niclaz** [comment]
That would make it less confusing in my book. 

In fact I looked for sats in the dropdown at first, almost instinctively, as this is a lightning-based service. 

All options are good, just sharing some feedback from first testing.

**Comment by rolznz** [comment]
@niclaz it is a lightning based service, but it's geared at onboarding people who have never used lightning/bitcoin. Hence the fiat currency.

Thanks, I'll let you know when this is fixed!

**Comment by rolznz** [comment]
I allow entering the right number of decimal points and automatically pick sats if you choose the BTC currency. Thanks for the bug report!
