### ISSUE TITLE
CONTRIBUTING.md needs to be updated

### ISSUE THREAD

**Issue by Wenze** [lightsats/lightsats#163]
I wanted to start translating but https://github.com/lightsats/lightsats/blob/main/CONTRIBUTING.md is outdated as it still mentions: _We use Weblate for Translations: https://hosted.weblate.org/projects/lightsats/_

**Comment by rolznz** [comment]
@Wenze thank you! are you ok to submit the translations as a github PR?

**Comment by Wenze** [comment]
> @Wenze thank you! are you ok to submit the translations as a github PR?

Yes, I will do so! I will work on the Dutch (Netherlands) translation.
