### ISSUE TITLE
Advertisement data not validated

### ISSUE THREAD

**Issue by Wenze** [lightsats/lightsats#165]
1. Both the URL and Image URL must exist. There is no front-end validation for this. When only adding one of them the Tip can still be created
2. Nothing is displayed to the receiver when only adding a URL/image.

https://github.com/lightsats/lightsats/blob/main/app/pages/journey/congratulations.tsx

![image](https://github.com/lightsats/lightsats/assets/3382304/06386b46-f839-4464-88ed-81d7614827eb)

**Comment by rolznz** [comment]
@Wenze thanks for reporting this! fix is up at https://lightsats.fly.dev/
