### ISSUE TITLE
Broken link on https://lightsats.com/guide/tip

### ISSUE THREAD

**Issue by GlenCooper** [lightsats/lightsats#205]
The link to ln.cash on https://lightsats.com/guide/tip is broken.

![Screenshot from 2023-12-29 16-50-43](https://github.com/lightsats/lightsats/assets/967793/b48db7a6-1281-4be0-a5a4-9587a3070eb3)

**Comment by GlenCooper** [comment]
![Screenshot from 2023-12-29 16-55-17](https://github.com/lightsats/lightsats/assets/967793/aa7a5c02-996f-4237-b31a-d7c25c58d786)

**Comment by rolznz** [comment]
Hi @GlenCooper thanks for reporting this!

Unfortunately it seems they shut down the site: https://twitter.com/lncash?lang=en

Probably it's best if we just remove that site from the guide.

**Comment by GlenCooper** [comment]
Confirmed removed.  Looks good now.  👍

![Screenshot from 2024-09-24 10-16-12](https://github.com/user-attachments/assets/48fa28c1-4c93-4ce5-a450-e1d16f10c3d1)

**Comment by GlenCooper** [comment]
Also, just for the record, here's what they had on their Twitter page;

https://x.com/lncash/status/1627489555619119105 | https://archive.ph/F7hHl
![Screenshot from 2024-09-24 10-20-20](https://github.com/user-attachments/assets/3528829f-e003-4a7b-a524-0188f047e265)

**Comment by rolznz** [comment]
Yeah, not good! thanks @GlenCooper  :scream:
