### ISSUE TITLE
Broken Withdrawals since 15/01/24 9am

### ISSUE THREAD

**Issue by Vix1818** [lightsats/lightsats#206]
I’ve been unable to withdraw tips since this morning; it looks like there might be a liquidity issue in your channels. This is inconvenient 😊

**Comment by Vix1818** [comment]
![IMG_2942](https://github.com/lightsats/lightsats/assets/156694050/7b27f8c4-7e8e-4ce9-a5d0-59decaddc433)
![IMG_2941](https://github.com/lightsats/lightsats/assets/156694050/c3c4e700-4e5f-4dcf-821e-ecc6f497a11e)

**Comment by Vix1818** [comment]
![IMG_2941](https://github.com/lightsats/lightsats/assets/156694050/2761c2fa-a782-40cb-9bc1-e6fa4a1ae3cb)
![IMG_2942](https://github.com/lightsats/lightsats/assets/156694050/2d9b826a-1905-4f3d-afc9-c19b2cb59dc4)

**Comment by rolznz** [comment]
Hi, thanks for reporting!

I can confirm I can deposit but not withdraw :/

I have asked our team member who manages the node liquidity to have a look.

**Comment by rolznz** [comment]
Hi @Vix1818 can you try again? the node was restarted and withdrawals seem to be working now.

**Comment by Vix1818** [comment]
Fixed 👍 GG team Lightsats ⚡️🧡

**Comment by rolznz** [comment]
Thanks for confirming!
