### ISSUE TITLE
passphraseLength is not documented in the API

### ISSUE THREAD

**Issue by dhalsim** [lightsats/lightsats#209]
Hey,

I found a bug while playing with the API in the create tip endpoint.

When I send `generatePassphrase` with value `true`, it is failing. I checked the code and found this:

```
const generatePassphraseFromRequest = (): string | undefined => {
  if (!createTipRequest.generatePassphrase) {
    return undefined;
  }
  if (
    isNaN(createTipRequest.passphraseLength) ||
    createTipRequest.passphraseLength < MIN_TIP_PASSPHRASE_LENGTH ||
    createTipRequest.passphraseLength > MAX_TIP_PASSPHRASE_LENGTH
  ) {
    throw new Error("Invalid tip passphrase length");
  }

  return generatePassphrase(createTipRequest.passphraseLength);
};
```

So actually `passphraseLength` is required if you want to use `generatePassphrase` according to code.

I think the best option is making `passphraseLength` optional, and if not provided set it with `MIN_TIP_PASSPHRASE_LENGTH`

Thanks a lot for the great product.
Best

**Comment by rolznz** [comment]
Thanks @dhalsim 

For now I decided to update the docs as there is not too much usage of this particular feature via the API. https://github.com/lightsats/Lightsats-API-docs/pull/1
