### ISSUE TITLE
Feature Request: Short coupon codes that you can write down on a piece of paper

### ISSUE THREAD

**Issue by oren-z0** [lightsats/lightsats#28]
Instead of sending sats to a specific user, I would like to attach funds to a random ~8 digits coupon code - for anyone could redeem.

For example as a tip in a restaurant (without the awkwardness of asking the waiter for his contact details). There could also be a captcha to solve, in order to block bots that try all possible codes.

It could also be nice to design a small note to print (the size of a business card), like:
```
+-----------------------------------------------+
|                Bitcoin Coupon!                |
|        Redeemable at www.lightsats.com        |
|           Coupon Code: ____________           |
|       Value: ________ sats ≈ $ ________       |
|           (dollar value may change)           |
|       Expiry date (optional): _________       |
|                                               |
|       Sats is the base unit of Bitcoin        |
|            like cents and dollars.            |
|         1 Bitcoin = 100,000,000 sats          |
+-----------------------------------------------+
```

Users could print several of these notes, keep in their wallet, and on the spot fill the missing placeholders and leave it as a tip.

Obviously the tipper could "steal the funds" knowing the coupon code, but then why would he tip in the first place...

I would also not force users to sign in to redeem the tip. I know that you want more signed-in users on your website, but most no-coiners might simply give up. There should be a "maybe later" button on the sign-in step.

**Comment by rolznz** [comment]
@oren-z0 

Would printing the QR code work? you can just give someone the qr code of a funded tip and ask them to scan it.

Signup is needed in the case where a user scans a QR code once but does not withdraw the funds immediately (maybe they don't have a wallet yet) and do not necessarily have access to that QR code again (sometimes they use an in-app browser and they are unable to access their history). There are many other benefits of signing up - the tipper can see the tippee's progress, and in the future there will be a communication channel if the tippee needs help. Their withdrawn tip will be in their history and they will be able to tip others through lightsats if they wish to. @juangb87 @reneaaron do you have any thoughts?

**Comment by reneaaron** [comment]
We also thought about having some pre-printed cards that you can create at home early on (something like https://www.bctip.org/de/) but wanted to focus on the digital experience for now. 

I am interested in learning about your use case though: 

Would having some lightsats printouts solve this issue for you? Or do you think it's important to be able to load those cards while you are at the restaurant?

**Comment by oren-z0** [comment]
@rolznz I think that forcing the a no-coiner to enter his email/phone-number to redeem, immediately makes him think that this is only for spam purposes, especially if the payer is not there to explain all the details. Like one of those scammy "You've won a free prize" ads.

My intention is to leave these coupon cards in restaurants instead of leaving 10%-15% cash tip (or whatever is customary in your countries). There is no law that obligates me to leave tip anyways, so why not leave a smaller amount in cash and the rest in Bitcoin? But it's very important that it would be easy enough for every waiter and waitress to redeem it - or else they'll just throw the coupon-card away, and give me bad attitude the next time I'll visit the place.

**Comment by rolznz** [comment]
Each funded tip has it's own QR code, so you don't need to worry about users trying to withdraw twice. We also plan to allow the tipper to update the tip at any time by scanning that same QR code, so they can add details to the tip to make it more authentic, for example adding the name of the restaurant and more.

I do agree that it would be cool for users to withdraw without signing up. Unfortunately in reality most nocoiners won't go through the full flow of downloading a wallet and withdrawing the funds in one go (unless you gave them a really big tip). Getting them to commit to login and claiming the funds is a great first step which helps them continue the process.

**Comment by oren-z0** [comment]
@rolznz I didn't talk about withdrawing twice. I was just worried about some user printing one QR code, seeing that it works, and then printing the same QR code again and again...

For no-coiners, if they happen to have Telegram, I would recommend one of the telegram bots: https://github.com/lightsats/lightsats/issues/29

The instructions could be as simple as:
```
Withdraw with Telegram:
1. Start a chat with @LightningTipBot (or enter https://ln.tips)
2. Enter: /lnurl LNURL... (click here to copy)
```

**Comment by reneaaron** [comment]
We can't really know which apps are installed on tipee phones, but we will add further wallet options as well and are thinking about allowing tippers to customize the options available (if you know they have Telegram you could select such a wallet as the recommendation). Do you think that would help for your case? 

I don't think Telegram wallets are the easiest option for people to get started though, I wouldn't want to confront people with commands, LNURL, etc as they just get started with bitcoin.

**Comment by murdawkmedia** [comment]
I came here to suggest the same thing! I've been using https://tipcards.sate.tools/ for the last few weeks and leaving a portion of my tip (in bitcoin) on printed QR code sheets. But - in a couple weeks I'll start going back and sweeping any unspent sats back. The implementation you have is awesome since it automates that process. 

As oren-Z0 says it is off putting asking the person you're tipping for their phone number or e-mail. Leaving behind a printed QR code or coupon on the fly would be awesome to have as an option.

**Comment by rolznz** [comment]
Small update: we are currently implementing bulk tip creation which will allow you to fund multiple in one go, and then print out as cards to give to people.

We do like the original idea especially since it does not require a printer. I have added it to the roadmap, hopefully we get to it soon!

**Comment by murdawkmedia** [comment]
Amazing! I'll be sure to try it out.

Cheers!

**Comment by niclaz** [comment]
@rolznz - just stumbled across Lightsats through Twitter and the Bitcoin Boracay project. 

Pretty cool to be honest, and I created an anon account to test i, then I saw a Twitter post pointing to the three word system you implemented for tips (this feature request)

Found it curious they were BIP39 words, and that the 'prefilled' words on the tip webpage were also BIP39 words... and to be honest I was a little bit shocked to see not captcha or limiter on the webpage. 

Were I a black-hat I would automate the input of 3 random BIP39 words into the form, and claim any tips that are valid. If my math is correct there are 1,429,559,296 combinations of 3 words from the 2048 (without repetitions), so it is a lottery but someone less ethically inclined may seek to implement this. 

I guess my suggestion is to rate-limit the submissions to this form or add a captcha (ideally not a Google one). That said, the tech is awesome and this is just a feature-request. 

FYI - I also tested the three words you added above in this issues and just claimed your easter egg - thanks for the 1 sat tip ;)

![lightsats tip in documentation](https://user-images.githubusercontent.com/83479948/218392800-8d2ed3b0-f78d-44a0-b4d7-90992d022456.png)

**Comment by reneaaron** [comment]
Hey @niclaz, glad you like our project and thanks for your inputs! 

> Found it curious they were BIP39 words, and that the 'prefilled' words on the tip webpage were also BIP39 words... and to be honest I was a little bit shocked to see not captcha or limiter on the webpage.

There are currently 2048^3 = 8.59 billion combinations, also we have some basic rate limits in place to prevent malicious actors from doing so. (it's not 100% bullet proof but given the amount you can potentially gather by brute-forcing those keys you will probably end up paying a lot more for the attack than you can gain). Also we could add another word (or captchas like you proposed) any time we see this happening...

**Comment by niclaz** [comment]
Hey @reneaaron thanks for correcting my calculations... I was thinking after posting that seemed awfully low 

Agreed that a brute-forcing of this page would probably not be economically viable to an attacker, as also these 3 word coupons only allow access to time-limited and small amounts of sats. 

To be honest I am spending some time digging through your code here just for my own interest on how you implemented the bip39 coupon mechanism - will send a secure message if I come across any other potential attack vectors. 

Keep innovating you all

**Comment by rolznz** [comment]
Just an update here - we have deployed another feature that allows you to print blank cards in bulk from the dashboard. You can then create the tips whenever you like, and write the 3 words onto the card.

This doesn't contain all the info in the original request as we wanted to keep it clean and simple, however we only print content on one side of the card, so feel free to add a personal message on the back.

I think this completes the original issue. Thanks everyone for your feedback! if you have any more thoughts, please open a new issue and we will be happy to discuss it further.

**Comment by murdawkmedia** [comment]
That sounds like a decent solution, I'm looking forward to passing out some
Sats in the wild!
