### ISSUE TITLE
Add Telegram lightning wallets to your recommended wallets

### ISSUE THREAD

**Issue by oren-z0** [lightsats/lightsats#29]
I found them to be the easiest to onboard new users that already have Telegram, especially https://ln.tips

**Comment by juangb87** [comment]
> I found them to be the easiest to onboard new users that already have Telegram, especially https://ln.tips

@oren-z0 we just added both ln.tips and lntxbot  to the wallet guides!
https://lightsats.com/guide/wallets
[![mobile-96.png](https://i.postimg.cc/Wb8CWNvz/mobile-96.png)](https://postimg.cc/Yh4djwjB)
