### ISSUE TITLE
Wrong default wallet on incognito browser in iOS

### ISSUE THREAD

**Issue by juangb87** [lightsats/lightsats#60]
When I go through the claim a tip flow using incognito browser the default wallet we are recommending  is Alby, I guess if it's in incognito browser we're not recognizing the user is on a mobile device. 

https://user-images.githubusercontent.com/52425945/205520714-2883ea58-8ed8-4c9e-8fc0-5b279ccfd866.MOV

**Comment by rolznz** [comment]
Fixed
