### ISSUE TITLE
Lightsats rejects email address with custom subdomain

### ISSUE THREAD

**Issue by sbddesign** [lightsats/lightsats#69]
When I try to add an email to my Lightsats account, it gives me an error message to the effect of "please use a valid email address". I am using a custom subdomain, like `name@my.sub.domain.com`. It is a perfectly valid email address, yet I think the form validation is rejecting it for not following a more common form like `@gmail.com`.

**Comment by rolznz** [comment]
@sbddesign I tried to login with the example format (name@my.sub.domain.com) and it worked without an error message. Can you double check your email is of that exact format?

**Comment by sbddesign** [comment]
@rolznz Strange, it's working for me now. Perhaps I fumbled something with my form input. Nevermind. Thanks!
